version: 0.0
os: linux

files:
  - source: ./appspec.yml
    destination: /home/ubuntu
  - source: /codedeploy/applicationStop.sh
    destination: /home/ubuntu
  - source: /codedeploy/beforeInstall.sh
    destination: /home/ubuntu
  - source: /codedeploy/afterInstall.sh
    destination: /home/ubuntu
  - source: /codedeploy/applicationStart.sh
    destination: /home/ubuntu
  - source: /codedeploy/validateService.sh
    destination: /home/ubuntu
  - source: ./ROOT.jar
    destination: /home/ubuntu
  - source: ./ROOT.war
    destination: /home/ubuntu

hooks:
  ApplicationStop:
    - location: /codedeploy/applicationStop.sh
      timeout: 180
      runas: ubuntu
  BeforeInstall:
    - location: /codedeploy/beforeInstall.sh
      timeout: 180
      runas: ubuntu
  ApplicationStart:
    - location: /codedeploy/applicationStart.sh
      timeout: 180
      runas: ubuntu
